"""Add last_energy_daily_kwh

Revision ID: 3e0aade6e727
Revises: 0002
Create Date: 2026-07-22 08:54:03.593300
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3e0aade6e727'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverters', sa.Column('last_energy_daily_kwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inverters', 'last_energy_daily_kwh')
    # ### end Alembic commands ###
